resolver: ghc-8.10
packages:
  - .
extra-deps:
  - adjunctions-4.4
  - criterion-1.5.13.0
  - deque-0.4.4
  - extra-1.7.10
  - kan-extensions-5.2.3
  - sbv-8.17
  - syb-0.7.2.1
  - tree-monad-0.3.1
  - Glob-0.10.2
  - QuickCheck-2.14.2
  - aeson-2.0.3.0
  - ansi-wl-pprint-0.6.9
  - async-2.2.4
  - base-compat-batteries-0.12.1
  - binary-orphans-1.0.2
  - cassava-0.5.2.0
  - clock-0.8.3
  - code-page-0.2.1
  - comonad-5.0.8
  - contravariant-1.5.5
  - criterion-measurement-0.1.3.0
  - distributive-0.6.2.1
  - free-5.1.7
  - hashable-1.4.0.2
  - invariant-0.5.5
  - js-chart-2.9.4.1
  - libBF-0.6.3
  - microstache-1.0.2
  - mwc-random-0.15.0.2
  - optparse-applicative-0.17.0.0
  - profunctors-5.6.2
  - random-1.2.1
  - semigroupoids-5.3.7
  - semigroups-0.20
  - statistics-0.16.0.2
  - strict-list-0.1.6
  - tagged-0.8.6.1
  - transformers-compat-0.7.1
  - uniplate-1.6.13
  - vector-0.12.3.1
  - vector-algorithms-0.8.0.4
  - void-0.7.3
  - OneTuple-0.3.1
  - Only-0.1
  - StateVar-1.2.2
  - ansi-terminal-0.11.1
  - attoparsec-0.14.4
  - base-compat-0.12.1
  - base-orphans-0.8.6
  - bifunctors-5.5.11
  - data-default-class-0.1.2.0
  - data-fix-0.3.2
  - dense-linear-algebra-0.1.0.0
  - dlist-1.0
  - indexed-traversable-0.1.2
  - math-functions-0.3.4.2
  - monad-par-0.3.5
  - primitive-0.7.3.0
  - scientific-0.3.7.0
  - semialign-1.2.0.1
  - splitmix-0.1.0.4
  - strict-0.4.0.1
  - text-short-0.1.5
  - th-abstraction-0.4.3.0
  - these-1.1.1.1
  - time-compat-1.9.6.1
  - transformers-base-0.4.6
  - unordered-containers-0.2.18.0
  - uuid-types-1.0.5
  - vector-binary-instances-0.2.5.2
  - vector-th-unbox-0.2.2
  - witherable-0.4.2
  - abstract-deque-0.3
  - abstract-par-0.3.3
  - assoc-1.0.2
  - colour-2.3.6
  - indexed-traversable-instances-0.1.1
  - integer-logarithms-1.0.3.1
  - monad-par-extras-0.3.3
  - parallel-3.2.2.0
  - cereal-0.5.8.2
